In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('NBA_player_stats_2019_raw.csv', encoding = "utf-8")
data.set_index('rank', inplace=True)
data

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
1,Álex Abrines,SG,25,OKC,31,2,588,56,157,0.357,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
2,Quincy Acy,PF,28,PHO,10,0,123,4,18,0.222,...,15.2,9.2,-0.1,0.0,-0.1,-0.022,-5.7,-0.3,-5.9,-0.1
3,Jaylen Adams,PG,22,ATL,34,1,428,38,110,0.345,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
4,Steven Adams,C,25,OKC,80,80,2669,481,809,0.595,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
5,Bam Adebayo,C,21,MIA,82,28,1913,280,486,0.576,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Tyler Zeller,C,29,MEM,4,1,82,16,28,0.571,...,10.0,21.8,0.2,0.1,0.3,0.191,-0.3,-1.3,-1.5,0.0
529,Ante Žižić,C,22,CLE,59,25,1082,183,331,0.553,...,13.6,18.2,1.7,0.3,2.0,0.087,-1.7,-1.4,-3.1,-0.3
530,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5
530,Ivica Zubac,C,21,LAL,33,12,516,112,193,0.580,...,12.9,20.5,1.1,0.6,1.8,0.165,-1.3,0.4,-0.9,0.1
530,Ivica Zubac,C,21,LAC,26,25,524,100,186,0.538,...,14.8,20.1,0.7,0.7,1.4,0.132,-1.2,1.5,0.3,0.3

In [3]:
data.isnull()

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
529,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
530,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
530,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
530,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
def nans(data): return data[data.isnull().any(axis=1)]
nans_df = nans(data)
nans_df

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
17,Ike Anigbogu,C,20,IND,3,0,6,0,3,0.000,...,25.0,29.1,-0.1,0.0,-0.1,-0.480,-22.5,8.5,-14.0,0.0
19,Kostas Antetokounmpo,PF,21,DAL,2,0,11,0,3,0.000,...,17.4,22.5,-0.1,0.0,-0.1,-0.247,-15.9,2.7,-13.3,0.0
28,Ron Baker,SG,25,WAS,4,0,45,0,4,0.000,...,33.3,5.7,-0.1,0.0,-0.1,-0.120,-8.8,0.8,-8.1,-0.1
47,Dairis Bertāns,SG,29,NOP,12,0,167,12,47,0.255,...,4.1,12.0,-0.2,0.0,-0.2,-0.054,-4.2,-3.5,-7.7,-0.2
51,Bismack Biyombo,C,26,CHO,54,32,783,89,156,0.571,...,14.8,12.7,1.2,0.8,2.0,0.125,-2.5,1.5,-1.1,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Tyler Zeller,C,29,MEM,4,1,82,16,28,0.571,...,10.0,21.8,0.2,0.1,0.3,0.191,-0.3,-1.3,-1.5,0.0
529,Ante Žižić,C,22,CLE,59,25,1082,183,331,0.553,...,13.6,18.2,1.7,0.3,2.0,0.087,-1.7,-1.4,-3.1,-0.3
530,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5
530,Ivica Zubac,C,21,LAL,33,12,516,112,193,0.580,...,12.9,20.5,1.1,0.6,1.8,0.165,-1.3,0.4,-0.9,0.1
530,Ivica Zubac,C,21,LAC,26,25,524,100,186,0.538,...,14.8,20.1,0.7,0.7,1.4,0.132,-1.2,1.5,0.3,0.3

In [5]:
nans_df.isna().any()

player       False
pos          False
age          False
team_id      False
g            False
             ...
ws_per_48    False
obpm         False
dbpm         False
bpm          False
vorp         False
Length: 103, dtype: bool

In [6]:
nans_df.loc[:, nans_df.isna().any()]

,fg_pct,fg3_pct,fg2_pct,efg_pct,ft_pct,off_rtg,ts_pct,fg3a_per_fga_pct,fta_per_fga_pct,tov_pct
rank,,,,,,,,,,
17,0.000,NaN,0.000,0.000,NaN,33.0,0.000,0.000,0.000,25.0
19,0.000,NaN,0.000,0.000,0.500,39.0,0.210,0.000,1.333,17.4
28,0.000,0.000,NaN,0.000,NaN,20.0,0.000,1.000,0.000,33.3
47,0.255,0.294,0.154,0.362,NaN,86.0,0.362,0.723,0.000,4.1
51,0.571,NaN,0.571,0.571,0.637,121.0,0.602,0.000,0.583,14.8
...,...,...,...,...,...,...,...,...,...,...
528,0.571,NaN,0.571,0.571,0.778,126.0,0.640,0.000,0.643,10.0
529,0.553,NaN,0.553,0.553,0.705,116.0,0.590,0.000,0.399,13.6
530,0.559,NaN,0.559,0.559,0.802,116.0,0.604,0.000,0.332,13.9
530,0.580,NaN,0.580,0.580,0.864,120.0,0.633,0.000,0.342,12.9
530,0.538,NaN,0.538,0.538,0.733,113.0,0.574,0.000,0.323,14.8

In [7]:
data = data.fillna(0)

In [8]:
data

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
1,Álex Abrines,SG,25,OKC,31,2,588,56,157,0.357,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
2,Quincy Acy,PF,28,PHO,10,0,123,4,18,0.222,...,15.2,9.2,-0.1,0.0,-0.1,-0.022,-5.7,-0.3,-5.9,-0.1
3,Jaylen Adams,PG,22,ATL,34,1,428,38,110,0.345,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
4,Steven Adams,C,25,OKC,80,80,2669,481,809,0.595,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
5,Bam Adebayo,C,21,MIA,82,28,1913,280,486,0.576,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Tyler Zeller,C,29,MEM,4,1,82,16,28,0.571,...,10.0,21.8,0.2,0.1,0.3,0.191,-0.3,-1.3,-1.5,0.0
529,Ante Žižić,C,22,CLE,59,25,1082,183,331,0.553,...,13.6,18.2,1.7,0.3,2.0,0.087,-1.7,-1.4,-3.1,-0.3
530,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5
530,Ivica Zubac,C,21,LAL,33,12,516,112,193,0.580,...,12.9,20.5,1.1,0.6,1.8,0.165,-1.3,0.4,-0.9,0.1
530,Ivica Zubac,C,21,LAC,26,25,524,100,186,0.538,...,14.8,20.1,0.7,0.7,1.4,0.132,-1.2,1.5,0.3,0.3

In [9]:
multiteam_df = data[data['team_id']=='TOT']
multiteam_df

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
16,Ryan Anderson,PF,30,TOT,25,8,322,21,69,0.304,...,15.5,12.0,-0.3,0.0,-0.2,-0.035,-4.5,-2.0,-6.4,-0.4
23,Trevor Ariza,SF,33,TOT,69,69,2349,294,736,0.399,...,11.6,16.6,1.3,1.2,2.5,0.052,-0.1,-0.4,-0.5,0.9
28,Ron Baker,SG,25,TOT,15,0,152,4,20,0.200,...,18.1,7.8,-0.2,0.1,-0.1,-0.034,-5.9,-0.7,-6.6,-0.2
33,Harrison Barnes,PF-SF,26,TOT,77,77,2533,431,1027,0.420,...,7.9,20.9,2.0,1.6,3.6,0.068,-0.6,-1.8,-2.3,-0.2
63,Avery Bradley,SG,28,TOT,63,63,1905,248,608,0.408,...,12.4,16.2,-0.6,1.0,0.3,0.009,-1.7,-1.0,-2.8,-0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,Jonas Valančiūnas,C,26,TOT,49,27,1091,301,538,0.559,...,12.7,28.5,2.2,1.9,4.2,0.183,0.1,1.2,1.2,0.9
521,Christian Wood,PF,23,TOT,21,2,251,61,117,0.521,...,10.7,26.1,0.4,0.3,0.8,0.151,-1.5,-1.8,-3.3,-0.1
522,Delon Wright,PG,26,TOT,75,13,1699,242,558,0.434,...,11.0,18.1,1.9,2.4,4.3,0.121,0.0,1.5,1.5,1.5
528,Tyler Zeller,C,29,TOT,6,1,93,16,30,0.533,...,9.5,20.1,0.2,0.1,0.3,0.167,-1.0,-1.2,-2.2,0.0
530,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5

In [10]:
name_list = multiteam_df['player'].tolist()

nototals_df = data[~data['player'].isin(name_list)]

In [11]:
nototals_df

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
rank,,,,,,,,,,,,,,,,,,,,,
1,Álex Abrines,SG,25,OKC,31,2,588,56,157,0.357,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
2,Quincy Acy,PF,28,PHO,10,0,123,4,18,0.222,...,15.2,9.2,-0.1,0.0,-0.1,-0.022,-5.7,-0.3,-5.9,-0.1
3,Jaylen Adams,PG,22,ATL,34,1,428,38,110,0.345,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
4,Steven Adams,C,25,OKC,80,80,2669,481,809,0.595,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
5,Bam Adebayo,C,21,MIA,82,28,1913,280,486,0.576,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,Nick Young,SG,33,DEN,4,0,37,3,9,0.333,...,18.2,12.7,0.0,0.0,0.0,-0.021,-4.4,-2.6,-7.0,0.0
525,Thaddeus Young,PF,30,IND,81,81,2489,443,841,0.527,...,12.0,18.0,3.0,3.9,6.9,0.133,0.8,2.1,2.9,3.1
526,Trae Young,PG,20,ATL,81,81,2503,525,1256,0.418,...,17.6,28.4,2.5,0.7,3.3,0.062,1.8,-2.8,-1.1,0.6
527,Cody Zeller,C,26,CHO,49,47,1243,190,345,0.551,...,13.2,16.3,2.6,1.2,3.9,0.150,0.2,1.7,2.0,1.2
529,Ante Žižić,C,22,CLE,59,25,1082,183,331,0.553,...,13.6,18.2,1.7,0.3,2.0,0.087,-1.7,-1.4,-3.1,-0.3

In [12]:
onlytotals_df = pd.concat([nototals_df,multiteam_df],ignore_index=True)
onlytotals_df

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
0,Álex Abrines,SG,25,OKC,31,2,588,56,157,0.357,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
1,Quincy Acy,PF,28,PHO,10,0,123,4,18,0.222,...,15.2,9.2,-0.1,0.0,-0.1,-0.022,-5.7,-0.3,-5.9,-0.1
2,Jaylen Adams,PG,22,ATL,34,1,428,38,110,0.345,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
3,Steven Adams,C,25,OKC,80,80,2669,481,809,0.595,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
4,Bam Adebayo,C,21,MIA,82,28,1913,280,486,0.576,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Jonas Valančiūnas,C,26,TOT,49,27,1091,301,538,0.559,...,12.7,28.5,2.2,1.9,4.2,0.183,0.1,1.2,1.2,0.9
526,Christian Wood,PF,23,TOT,21,2,251,61,117,0.521,...,10.7,26.1,0.4,0.3,0.8,0.151,-1.5,-1.8,-3.3,-0.1
527,Delon Wright,PG,26,TOT,75,13,1699,242,558,0.434,...,11.0,18.1,1.9,2.4,4.3,0.121,0.0,1.5,1.5,1.5
528,Tyler Zeller,C,29,TOT,6,1,93,16,30,0.533,...,9.5,20.1,0.2,0.1,0.3,0.167,-1.0,-1.2,-2.2,0.0
529,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5

In [13]:
# result = result[(result['var']>0.25) | (result['var']<-0.25)]
# playtime_df = onlytotals_df[(onlytotals_df['mp']>200) | (onlytotals_df['g']>8)]
playtime_df = onlytotals_df[(onlytotals_df['g']>8)]
playtime_df = onlytotals_df[(onlytotals_df['mp']>200)]
playtime_df

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
0,Álex Abrines,SG,25,OKC,31,2,588,56,157,0.357,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
2,Jaylen Adams,PG,22,ATL,34,1,428,38,110,0.345,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
3,Steven Adams,C,25,OKC,80,80,2669,481,809,0.595,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
4,Bam Adebayo,C,21,MIA,82,28,1913,280,486,0.576,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4
7,LaMarcus Aldridge,C,33,SAS,81,81,2687,684,1319,0.519,...,8.8,26.9,6.4,2.9,9.3,0.167,1.2,0.5,1.6,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,Garrett Temple,SG,32,TOT,75,55,2040,208,493,0.422,...,11.5,13.2,0.3,2.0,2.2,0.052,-1.7,0.6,-1.2,0.4
525,Jonas Valančiūnas,C,26,TOT,49,27,1091,301,538,0.559,...,12.7,28.5,2.2,1.9,4.2,0.183,0.1,1.2,1.2,0.9
526,Christian Wood,PF,23,TOT,21,2,251,61,117,0.521,...,10.7,26.1,0.4,0.3,0.8,0.151,-1.5,-1.8,-3.3,-0.1
527,Delon Wright,PG,26,TOT,75,13,1699,242,558,0.434,...,11.0,18.1,1.9,2.4,4.3,0.121,0.0,1.5,1.5,1.5
529,Ivica Zubac,C,21,TOT,59,37,1040,212,379,0.559,...,13.9,20.3,1.9,1.3,3.2,0.148,-1.2,1.0,-0.3,0.5

In [14]:
playtime_df.loc[playtime_df['player'].str.contains('Dario')]

,player,pos,age,team_id,g,gs,mp,fg,fga,fg_pct,...,tov_pct,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp
512,Dario Šarić,PF,24,TOT,81,41,2023,304,696,0.437,...,11.3,17.8,2.3,1.2,3.5,0.084,0.3,-1.4,-1.1,0.5

In [15]:
playtime_df["player"]= playtime_df["player"].str.replace("Álex Abrines", "Alex Abrines", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Jonas Valančiūnas", "Jonas Valanciunas", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("José Calderón", "Jose Calderon", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Dāvis Bertāns", "Davis Bertans", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Bogdan Bogdanović", "Bogdan Bogdanovic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Bojan Bogdanović", "Bojan Bogdanovic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Luka Dončić", "Luka Doncic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Goran Dragić", "Goran Dragic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Cristiano Felício", "Cristiano Felicio", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Juan Hernangómez", "Juan Hernangomez", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Willy Hernangómez", "Willy Hernangomez", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Nenê Hilário", "Nene Hilario", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Ersan İlyasova", "Ersan Ilyasova", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Nikola Jokić", "Nikola Jokic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Nikola Vučević", "Nikola Vucevic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Nikola Mirotić", "Nikola Mirotic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Jusuf Nurkić", "Jusuf Nurkic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Jakob Pöltl", "Jakob Poetl", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Tomáš Satoranský", "Tomas Satoransky", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Dennis Schröder", "Dennis Schroeder", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Ante Žižić", "Ante Zizic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Timothé Luwawu-Cabarrot", "Timothe Luwawu-Cabarrot", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Boban Marjanović", "Boban Marjanovic", case = False)
playtime_df["player"]= playtime_df["player"].str.replace("Dario Šarić", "Dario Saric", case = False)

C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\kdola\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
playtime_df.to_csv('nba_data.csv', encoding='utf-8')